using System;
using static OpenMPT.NET.MptNative;

namespace OpenMPT.NET;

public unsafe struct RenderParams
{
    private const int MasterGainMillibel = 1;
    private const int StereoSeparationPercent = 2;
    private const int RenderInterpolationFilterLength = 3;
    private const int VolumeRampingStrength = 4;
    
    private readonly IntPtr _module;

    public RenderParams(IntPtr module)
    {
        _module = module;
    }
    
    /// <summary>
    /// Master Gain.<br />
    /// The related value represents a relative gain in milliBel.
    /// The default value is 0.
    /// The supported value range is unlimited.
    /// </summary>
    public int MasterGain
    {
        get
        {
            int value;
            ModuleGetRenderParam(_module, MasterGainMillibel, &value);
            return value;
        }
        set => ModuleSetRenderParam(_module, MasterGainMillibel, value);
    }

    /// <summary>
    /// Stereo Separation.<br />
    /// The related value represents the stereo separation generated by the libopenmpt mixer in percent.
    /// The default value is 0.5.
    /// The supported value range is [0,1].
    /// </summary>
    public float StereoSeparation
    {
        get
        {
            int value;
            ModuleGetRenderParam(_module, StereoSeparationPercent, &value);
            return value / 200.0f;
        }
        set => ModuleSetRenderParam(_module, StereoSeparationPercent, (int) (value * 200));
    }

    /// <summary>
    /// Interpolation Filter.<br />
    ///The related value represents the interpolation filter length used by the libopenmpt mixer.
    /// </summary>
    public Filter InterpolationFilter
    {
        get
        {
            int value;
            ModuleGetRenderParam(_module, RenderInterpolationFilterLength, &value);
            return (Filter) value;
        }
        set => ModuleSetRenderParam(_module, RenderInterpolationFilterLength, (int) value);
    }

    /// <summary>
    /// Volume Ramping Strength.<br />
    /// The related value represents the amount of volume ramping done by the libopenmpt mixer.
    /// The default value is -1, which indicates a recommended default value.
    /// The meaningful value range is [-1..10].
    /// A value of 0 completely disables volume ramping. This might cause clicks in sound output.
    /// Higher values imply slower/softer volume ramps. 
    /// </summary>
    public int VolumeRamping
    {
        get
        {
            int value;
            ModuleGetRenderParam(_module, VolumeRampingStrength, &value);
            return value;
        }
        set => ModuleSetRenderParam(_module, VolumeRampingStrength, value);
    }
}